//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15
use chrono::NaiveDateTime as DateTime;
use sea_orm::{entity::prelude::*, Set};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sessions")]
pub struct Model {
    pub created_at: DateTime,
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub pid: Uuid,
    pub user_id: i32,
    pub user_agent: String,
    pub ip: String,
    pub status: SessionStatus,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

#[async_trait::async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C>(self, _db: &C, insert: bool) -> Result<Self, DbErr>
    where
        C: ConnectionTrait,
    {
        if insert {
            let mut this = self;
            this.pid = Set(Uuid::new_v4());
            Ok(this)
        } else {
            Ok(self)
        }
    }
}

#[derive(
    EnumIter, DeriveActiveEnum, Clone, Debug, Eq, PartialEq, Serialize, Deserialize, Default,
)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::N(10))")]
pub enum SessionStatus {
    #[default]
    #[sea_orm(string_value = "active")] //default
    Active,
    #[sea_orm(string_value = "inactive")]
    Inactive,
}
impl TryFrom<String> for SessionStatus {
    type Error = sea_orm::DbErr;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        match value.as_str() {
            "active" => Ok(SessionStatus::Active),
            "inactive" => Ok(SessionStatus::Inactive),
            _ => Err(sea_orm::DbErr::Custom(format!("Invalid status: {}", value))),
        }
    }
}
impl TryFrom<SessionStatus> for String {
    type Error = sea_orm::DbErr;

    fn try_from(value: SessionStatus) -> Result<Self, Self::Error> {
        match value {
            SessionStatus::Active => Ok("active".to_string()),
            SessionStatus::Inactive => Ok("inactive".to_string()),
        }
    }
}
