//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15
use chrono::{NaiveDateTime as DateTime, Utc};
use sea_orm::{entity::prelude::*, Set};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user_login")]
pub struct Model {
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub last_used_at: DateTime,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: i32,
    pub strategy: LoginStrategy,
    pub value: Option<String>,
}

#[derive(EnumIter, DeriveActiveEnum, Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::N(10))")]
pub enum LoginStrategy {
    #[sea_orm(string_value = "password")]
    Password,
    #[sea_orm(string_value = "magic_link")]
    MagicLink,
    #[sea_orm(string_value = "google")]
    Google,
}

impl TryFrom<&str> for LoginStrategy {
    type Error = sea_orm::error::DbErr;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        match value {
            "password" => Ok(LoginStrategy::Password),
            "magic_link" => Ok(LoginStrategy::MagicLink),
            "google" => Ok(LoginStrategy::Google),
            _ => Err(sea_orm::error::DbErr::Custom(
                "Invalid login strategy".to_string(),
            )),
        }
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

#[async_trait::async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C>(mut self, _db: &C, insert: bool) -> Result<Self, DbErr>
    where
        C: ConnectionTrait,
    {
        if insert {
            self.last_used_at = Set(Utc::now().naive_utc());
        }
        Ok(self)
    }
}
