//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15
use chrono::NaiveDateTime as DateTime;
use migration::sea_orm;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Default, Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "jobs")]
pub struct Model {
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub job_id: String,
    pub queue: String,
    pub payload: Option<String>,
    pub job_type: JobType,
    pub status: JobStatus,
    pub retries: i32, // Every retry should spawn a new job
    pub max_retries: i32,
    pub last_ran_at: Option<DateTime>,  // Last ran at
    pub next_run_at: Option<DateTime>,  // Next expected run time
    pub completed_at: Option<DateTime>, // completed time ran at
    pub failed_at: Option<DateTime>,    // failed time
    pub linked_job_id: Option<i32>,     // Linked job id
    pub output: Option<String>,
    pub pattern: Option<String>, // CRON Pattern
    pub delay: i32,              // Delay in milliseconds
                                 // Add Back off later
}
#[derive(
    Default, EnumIter, DeriveActiveEnum, Clone, Debug, Eq, PartialEq, Serialize, Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::N(10))")]
pub enum JobStatus {
    #[default]
    #[sea_orm(string_value = "Active")]
    Active,
    #[sea_orm(string_value = "Completed")]
    Completed,
    #[sea_orm(string_value = "Running")]
    Running,
    #[sea_orm(string_value = "Failed")]
    Failed,
    #[sea_orm(string_value = "Cancelled")]
    Cancelled,
}
#[derive(
    Default, EnumIter, DeriveActiveEnum, Clone, Debug, Eq, PartialEq, Serialize, Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::N(20))")]
pub enum JobType {
    /// Trigger immediately on create or on start up
    #[default]
    #[sea_orm(string_value = "IMMEDIATE")]
    Immediate,
    /// Delayed jobs will spawn run after the specified delay in milliseconds
    #[sea_orm(string_value = "DELAYED")]
    Delayed,
    /// Scheduled jobs will spawn immediate jobs at the specified time in milliseconds
    #[sea_orm(string_value = "SCHEDULE")]
    Schedule,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(belongs_to = "Entity", from = "Column::LinkedJobId", to = "Column::Id")]
    SelfReferencing,
}

pub struct SelfReferencingLink;

impl Linked for SelfReferencingLink {
    type FromEntity = Entity;

    type ToEntity = Entity;

    fn link(&self) -> Vec<RelationDef> {
        vec![Relation::SelfReferencing.def()]
    }
}

impl ActiveModel {}

#[async_trait::async_trait]
impl ActiveModelBehavior for ActiveModel {}
